#large scale.yaml
alns_params:
    max_iterations: 10000
    q_learning:
        learning_rate: 0.01
        discount_factor: 0.95
genetic_algorithm_params:
    population_size: 1000
    mutation_rate: 0.01
