# small_scale.yaml
alns_params:
    max_iterations: 1000
    q_learning:
        learning_rate: 0.1
        discount_factor: 0.9
genetic_algorithm_params:
    population_size: 100
    mutation_rate: 0.05